"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\RESTDWCoreDesign.dcr" "Core.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\ShellTools\RESTDWShellServicesDesign.dcr" "ShellServices.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\Connectors\Indy\RESTDWSocketIndyDesign.dcr" "SocketIndy.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\Connectors\Ics\RESTDWSocketIcsDesign.dcr" "SocketIcs.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\Drivers\FireDAC\RESTDWDriverFireDAC.dcr" "DriverFireDAC.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\Drivers\UniDAC\RESTDWDriverUNIDAC.dcr" "DriverUNIDAC.rc"
"D:\IDE\Embarcadero\Studio\7\Bin\brcc32.exe" -fo "..\..\Packages\Delphi\Drivers\Zeos\RESTDWDriverZEOS.dcr" "DriverZEOS.rc"