{ $HDR$}
{**********************************************************************}
{ Unit archived using Team Coherence                                   }
{ Team Coherence is Copyright 2002 by Quality Software Components      }
{                                                                      }
{ For further information / comments, visit our WEB site at            }
{ http://www.TeamCoherence.com                                         }
{**********************************************************************}
{}
{ $Log:  16372: Interop.pas 
{
{   Rev 1.0    25/2/2003 13:26:42  GGrieve
}
{
IndySOAP: DUnit Tests
}
{
Version History:
  15 Aug 2002   Grahame Grieve                  Live SoapBuilders tests in DUnit testing
}

Unit Interop;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file://SoapBuilders\Interop.wsdl
Date:     13/8/2002 22:13:29
IndySoap: V0.01
---------------------------------------------------------------------------}

Interface

Uses
  Classes,
  IdSoapClient,
  IdSoapDateTime,
  IdSoapTypeRegistry;

Type

  SOAPStruct = class;

  ArrayOfSOAPStruct = array of SOAPStruct;
  ArrayOffloat = array of Single;
  ArrayOfint = array of Integer;
  ArrayOfstring = array of String;

  SOAPStruct = class (TIdBaseSoapableClass)
  Private
    FvarString : String;
    FvarInt : Integer;
    FvarFloat : Single;
  Published
    property varString : String read FvarString write FvarString;
    property varInt : Integer read FvarInt write FvarInt;
    property varFloat : Single read FvarFloat write FvarFloat;
  end;

  {Soap Address for this Interface: http://localhost/soap/}
  InteropTest = Interface (IIdSoapInterface) ['{6B1D35E6-CEC0-48A9-AF5B-51DC8127A761}']
       {!Namespace:http://soapinterop.org/; SoapAction: urn:soapinterop; Type: SOAPStruct = in http://soapinterop.org/xsd}
    function  echoString(inputString : String) : String; stdcall;
    function  echoStringArray(inputStringArray : ArrayOfstring) : ArrayOfstring; stdcall;
    function  echoInteger(inputInteger : Integer) : Integer; stdcall;
    function  echoIntegerArray(inputIntegerArray : ArrayOfint) : ArrayOfint; stdcall;
    function  echoFloat(inputFloat : Single) : Single; stdcall;
    function  echoFloatArray(inputFloatArray : ArrayOffloat) : ArrayOffloat; stdcall;
    function  echoStruct(inputStruct : SOAPStruct) : SOAPStruct; stdcall;
    function  echoStructArray(inputStructArray : ArrayOfSOAPStruct) : ArrayOfSOAPStruct; stdcall;
    procedure echoVoid; stdcall;
    function  echoBase64(inputBase64 : TStream) : TStream; stdcall;
    function  echoDate(inputDate : TIdSoapDateTime) : TIdSoapDateTime; stdcall;
  end;

function GetInteropTest(AClient : TIdSoapBaseSender = nil) : InteropTest;

Implementation

uses
  IdSoapClientHTTP,
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;



var 
  GClient : TIdSoapClientHTTP;

function GetInteropTest(AClient : TIdSoapBaseSender = nil) : InteropTest;
begin
  if not assigned(AClient) then
    begin
    if not assigned(GClient) then
      begin
      GClient := TIdSoapClientHTTP.create(nil);
      GClient.SoapURL := 'http://localhost/soap/';
      end;
    AClient := GClient;
    end;
  result := IdSoapD4Interface(AClient) as InteropTest;
end;

Initialization
  IdSoapRegisterType(TypeInfo(ArrayOfSOAPStruct), '', TypeInfo(SOAPStruct));
  IdSoapRegisterType(TypeInfo(SOAPStruct));
  IdSoapRegisterType(TypeInfo(ArrayOffloat), '', TypeInfo(Single));
  IdSoapRegisterType(TypeInfo(ArrayOfint), '', TypeInfo(Integer));
  IdSoapRegisterType(TypeInfo(ArrayOfstring), '', TypeInfo(String));
End.
