{ $HDR$}
{**********************************************************************}
{ Unit archived using Team Coherence                                   }
{ Team Coherence is Copyright 2002 by Quality Software Components      }
{                                                                      }
{ For further information / comments, visit our WEB site at            }
{ http://www.TeamCoherence.com                                         }
{**********************************************************************}
{}
{ $Log:  16370: Interop2GroupB.pas 
{
{   Rev 1.1    19/6/2003 21:36:56  GGrieve
{ Version #1
}
{
{   Rev 1.0    25/2/2003 13:26:36  GGrieve
}
{
Version History:
  19 Jun 2003   Grahame Grieve                  Fix array property registration
}

Unit Interop2GroupB;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file:C:\IndyLive\SOAP\dunit\WsdlSamples\Interop2GroupB.wsdl
Date:     13/9/2002 23:22:07
IndySoap: V0.02
---------------------------------------------------------------------------}

Interface

Uses
  IdSoapClient,
  IdSoapTypeRegistry,
  Interop2Base;

Type

  TSOAPArrayStruct = class;
  TSOAPStructStruct = class;

  TArrayOfString2 = array of TArrayOfString;

  TSOAPArrayStruct = class (TIdBaseSoapableClass)
  Private
    FvarString : String;
    FvarInt : Integer;
    FvarFloat : Single;
    FvarArray : TArrayOfString;
  Public
    Destructor Destroy; override;
    property varArray : TArrayOfString read FvarArray write FvarArray;
  Published
    property varString : String read FvarString write FvarString;
    property varInt : Integer read FvarInt write FvarInt;
    property varFloat : Single read FvarFloat write FvarFloat;
  end;

  TSOAPStructStruct = class (TIdBaseSoapableClass)
  Private
    FvarString : String;
    FvarInt : Integer;
    FvarFloat : Single;
    FvarStruct : TSOAPStruct;
  Published
    property varString : String read FvarString write FvarString;
    property varInt : Integer read FvarInt write FvarInt;
    property varFloat : Single read FvarFloat write FvarFloat;
    property varStruct : TSOAPStruct read FvarStruct write FvarStruct;
  end;

  {Soap Address for this Interface: http://www.mssoapinterop.org:80/Remoting/ServiceB.soap}
  IInteropService2B = Interface (IIdSoapInterface) ['{20ECF323-A65D-464B-A283-43272E6CCB40}']
       {!Namespace: http://soapinterop.org/;
         SoapAction: http://soapinterop.org/;
         Type: TArrayOffloat = ArrayOffloat in http://soapinterop.org/xsd;
         Type: TArrayOfint = ArrayOfint in http://soapinterop.org/xsd;
         Type: TArrayOfSOAPStruct = ArrayOfSOAPStruct in http://soapinterop.org/xsd;
         Type: TArrayOfstring = ArrayOfstring in http://soapinterop.org/xsd;
         Type: TArrayOfString2 = ArrayOfArrayOfString in http://soapinterop.org/xsd;
         Type: TSOAPStruct = SOAPStruct in http://soapinterop.org/xsd;
         Type: TSOAPArrayStruct = SOAPArrayStruct in http://soapinterop.org/xsd;
         Type: TSOAPStructStruct = SOAPStructStruct in http://soapinterop.org/xsd}
    function  echoSimpleTypesAsStruct(inputString : String; inputInteger : Integer; inputFloat : Single) : TSOAPStruct; stdcall;
    function  echo2DStringArray(input2DStringArray : TArrayOfString2) : TArrayOfString2; stdcall;
    function  echoNestedStruct(inputStruct : TSOAPStructStruct) : TSOAPStructStruct; stdcall;
    function  echoNestedArray(inputStruct : TSOAPArrayStruct) : TSOAPArrayStruct; stdcall;
    procedure echoStructAsSimpleTypes(inputStruct : TSOAPStruct; out outputString : String; out outputInteger : Integer; out outputFloat : Single); stdcall;
  end;

function GetInteropServiceB(AClient : TIdSoapBaseSender) : IInteropService2B;

Implementation

{$R Interop2GroupB.res}

uses
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;

{ TSOAPArrayStruct }

destructor TSOAPArrayStruct.destroy;
begin
  SetLength(FvarArray, 0);
  inherited;
end;

function GetInteropServiceB(AClient : TIdSoapBaseSender) : IInteropService2B;
begin
  result := IdSoapD4Interface(AClient) as IInteropService2B;
end;

Initialization
  IdSoapRegisterType(TypeInfo(TArrayOfstring2), '', TypeInfo(String));
  IdSoapRegisterType(TypeInfo(TSOAPArrayStruct));
  IdSoapRegisterProperty('TSOAPArrayStruct', 'varArray',
                   IdSoapFieldProp(@TSOAPArrayStruct(nil).FvarArray),
                   IdSoapFieldProp(@TSOAPArrayStruct(nil).FvarArray),
                   TypeInfo(TArrayOfString));
  IdSoapRegisterType(TypeInfo(TSOAPStructStruct));
End.
