{ $HDR$}
{**********************************************************************}
{ Unit archived using Team Coherence                                   }
{ Team Coherence is Copyright 2002 by Quality Software Components      }
{                                                                      }
{ For further information / comments, visit our WEB site at            }
{ http://www.TeamCoherence.com                                         }
{**********************************************************************}
{}
{ $Log:  16368: Interop2Base.pas 
{
{   Rev 1.0    25/2/2003 13:26:32  GGrieve
}
Unit Interop2Base;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file:InteropTest.wsdl
Date:     12/9/2002 23:14:01
IndySoap: V0.02
---------------------------------------------------------------------------}

Interface

Uses
  Classes,
  IdSoapClient,
  IdSoapDateTime,
  IdSoapTypeRegistry;

Type

  TSOAPStruct = class;

  TArrayOfSOAPStruct = array of TSOAPStruct;
  TArrayOffloat = array of Single;
  TArrayOfint = array of Integer;
  TArrayOfstring = array of String;

  TSOAPStruct = class (TIdBaseSoapableClass)
  Private
    FvarString : String;
    FvarInt : Integer;
    FvarFloat : Single;
  Published
    property varString : String read FvarString write FvarString;
    property varInt : Integer read FvarInt write FvarInt;
    property varFloat : Single read FvarFloat write FvarFloat;
  end;


  {Soap Address for this Interface: http://soap.4s4c.com/ilab/soap.asp}
  InteropTest2 = Interface (IIdSoapInterface) ['{30EF41B2-E31C-43AC-A2C5-1C049240E0ED}']
       {!Namespace: http://soapinterop.org/;
         SoapAction: http://soapinterop.org/;
         Type: TArrayOffloat = ArrayOffloat in http://soapinterop.org/xsd;
         Type: TArrayOfint = ArrayOfint in http://soapinterop.org/xsd;
         Type: TArrayOfSOAPStruct = ArrayOfSOAPStruct in http://soapinterop.org/xsd;
         Type: TArrayOfstring = ArrayOfstring in http://soapinterop.org/xsd;
         Type: TSOAPStruct = SOAPStruct in http://soapinterop.org/xsd}
    function  echoString(inputString : String) : String; stdcall;
    function  echoStringArray(inputStringArray : TArrayOfstring) : TArrayOfstring; stdcall;
    function  echoInteger(inputInteger : Integer) : Integer; stdcall;
    function  echoIntegerArray(inputIntegerArray : TArrayOfint) : TArrayOfint; stdcall;
    function  echoFloat(inputFloat : Single) : Single; stdcall;
    function  echoFloatArray(inputFloatArray : TArrayOffloat) : TArrayOffloat; stdcall;
    function  echoStruct(inputStruct : TSOAPStruct) : TSOAPStruct; stdcall;
    function  echoStructArray(inputStructArray : TArrayOfSOAPStruct) : TArrayOfSOAPStruct; stdcall;
    procedure echoVoid; stdcall;
    function  echoBase64(inputBase64 : TStream) : TStream; stdcall;
    function  echoDate(inputDate : TIdSoapDateTime) : TIdSoapDateTime; stdcall;
    function  echoHexBinary(inputHexBinary : THexStream) : THexStream; stdcall;
    function  echoDecimal(inputDecimal : Currency) : Currency; stdcall;
    function  echoBoolean(inputBoolean : Boolean) : Boolean; stdcall;
  end;

function GetInteropTest2(AClient : TIdSoapBaseSender) : InteropTest2;

Implementation

{$R Interop2Base.res}

uses
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;



function GetInteropTest2(AClient : TIdSoapBaseSender) : InteropTest2;
begin
  result := IdSoapD4Interface(AClient) as InteropTest2;
end;

Initialization
  IdSoapRegisterType(TypeInfo(TArrayOfSOAPStruct), '', TypeInfo(TSOAPStruct));
  IdSoapRegisterType(TypeInfo(TSOAPStruct));
  IdSoapRegisterType(TypeInfo(TArrayOffloat), '', TypeInfo(Single));
  IdSoapRegisterType(TypeInfo(TArrayOfint), '', TypeInfo(Integer));
  IdSoapRegisterType(TypeInfo(TArrayOfstring), '', TypeInfo(String));
End.
